### PR TITLE
Coinsturn cover request 

### PR DESCRIPTION
**Pull request by adriancorebooks**
When submitting a new or existing set details change, make sure you have followed the following steps:

### Adding New Set Details
- [x]  Add a new file (or update existing file) into the `set-details` or `set-details-polygon` folder that is named as `[insert-your-set-address].setdetails.json` (i.e. 0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b.setdetails.json). Make sure to provide the [checksum address](https://ethsum.netlify.app/) for your Set
- [x] Verify the JSON follows the correct schema according to this [template](https://github.com/SetProtocol/uniswap-tokenlist/blob/main/set-details.schema.json). You can verify it by pasting the schema into this [schema validator](https://www.jsonschemavalidator.net) and checking if your input JSON matches properly. If you need to have multi-line JSON, you can use a HJSON converter to help with writing it and then paste in the final valid JSON spit out from it (see README for example)
- [x] If adding brand new token, make sure to add it to the `set.tokenlist.json` or `set.polygon.tokenlist.json` as well following the correct schema from Uniswap: https://github.com/Uniswap/token-lists/blob/master/src/tokenlist.schema.json

### Updating Existing Set Details
- [x] If updating existing set details, update the version number appropriately (see the JSON schema above for version numbering explanation).
- [x] When generating a signature, make sure the version signed is for the one reflected in the version details for your entry.

### Signature (Required)

- [x] Attach the proper signature. You can generate one by going to the page for your Set on TokenSets and signing in. Tap on your Set's name and follow the instructions provided (i.e. 0x21fbf0696d5e0aa2ef41a2b4ffb623bcaf070461d61cf7251c74161f82fec3a4370854bc0a34b3ab487c1bc021cd318c734c51ae29374f2beb0e6f2dd49b4bf41c):

[0xa3332bf673586ba02ff37b3b3eeea3c41a72e1baeef8b52bac5b6c684125724d35077151c4bfb1ad486cb078fb39b46d274393448a7ca0af65c75869cabe0fe701]

### CODE REVIEW

**Review by ADWilkinson — COMMENTED** [review]
have you added these changes to the entry in set.tokenlist.json?

**Comment by adriancorebooks** [comment]
Yes. ¿what is the approximate time for them to accept the merge?

**Comment by adriancorebooks** [comment]
> have you added these changes to the entry in set.tokenlist.json?

YES

**Comment by cleqo** [comment]
Hi, we have already created a pool for our token set, in the next weeks we are planning to add 1M usd in our liquidity pools, could you help us adding the lisiting so more users can find our token in Uni and other platforms? 

https://info.uniswap.org/#/pools/0x680063f1fdc795f08e730416352275b9b2832256

**Comment by adriancorebooks** [comment]
@ADWilkinson  the changes are ready

**Comment by justinkchen** [comment]
Looks like this is still missing an entry in set.tokenlist.json

**Comment by justinkchen** [comment]
Also the file name needs to be the checksummed version, not the all lower case version

**Pull request closed without merging**
