### PR TITLE
WLKR Innovation

### PR DESCRIPTION
**Pull request by samisbakedham**
Message Signature:
0x20d0ea29310b3d58a5b7fdb71ddd05718935928dc2856cd386b8f991b7c25f24470daeaa0577be3b1620bfd36f23a9007c854a4acdcd612365d53418a75ddc171c

When submitting a new or existing set details change, make sure you have followed the following steps:

### Adding New Set Details
- [x]  Add a new file (or update existing file) into the `set-details` or `set-details-polygon` folder that is named as `[insert-your-set-address].setdetails.json` (i.e. 0x1494CA1F11D487c2bBe4543E90080AeBa4BA3C2b.setdetails.json). Make sure to provide the [checksum address](https://ethsum.netlify.app/) for your Set
- [x] Verify the JSON follows the correct schema according to this [template](https://github.com/SetProtocol/uniswap-tokenlist/blob/main/set-details.schema.json). You can verify it by pasting the schema into this [schema validator](https://www.jsonschemavalidator.net) and checking if your input JSON matches properly. If you need to have multi-line JSON, you can use a HJSON converter to help with writing it and then paste in the final valid JSON spit out from it (see README for example)
- [x] If adding brand new token, make sure to add it to the `set.tokenlist.json` or `set.polygon.tokenlist.json` as well following the correct schema from Uniswap: https://github.com/Uniswap/token-lists/blob/master/src/tokenlist.schema.json

### Signature (Required)

- [x] Attach the proper signature. You can generate one by going to the page for your Set on TokenSets and signing in. Tap on your Set's name and follow the instructions provided (i.e. 0x21fbf0696d5e0aa2ef41a2b4ffb623bcaf070461d61cf7251c74161f82fec3a4370854bc0a34b3ab487c1bc021cd318c734c51ae29374f2beb0e6f2dd49b4bf41c):

0x20d0ea29310b3d58a5b7fdb71ddd05718935928dc2856cd386b8f991b7c25f24470daeaa0577be3b1620bfd36f23a9007c854a4acdcd612365d53418a75ddc171c

### CODE REVIEW

**Review by samisbakedham — COMMENTED** [review]
Double Checked.

**Comment by samisbakedham** [comment]
Merge?

**Comment by samisbakedham** [comment]
Should've been merged yesterday

**Comment by samisbakedham** [comment]
Fixed direct logo link references, removed .DS_Store files. Thank you for the heads up!

**Review by ADWilkinson — APPROVED** [review]

**Pull request merged**
