### PR TITLE
Change svg to png

### PR DESCRIPTION
**Pull request by lxgn**
Fix problem with images. Change svg to png

### CODE REVIEW

**Comment by asoong** [comment]
Get in the habit of submitting with new version signature and including in pull request.

**Comment by asoong** [comment]
Rebase, include signature.

**Comment by lxgn** [comment]
> Rebase, include signature.

double-check the instructions, there is no longer that signature method on the tokenset. We checked it 4 times, and the last time the addition was allowed to be made without it.

**Comment by asoong** [comment]
You must be logged in as the admin in order to generate the signature. Can you rebase master from this branch?

**Comment by lxgn** [comment]
> You must be logged in as the admin in order to generate the signature. Can you rebase master from this branch?

yes, the login to the tokenset is through the creator's wallet.

**Comment by lxgn** [comment]
https://www.tokensets.com/v2/set/0xe5feeaC09D36B18b3FA757E5Cf3F8dA6B8e27F4C

**Comment by asoong** [comment]
Stale branch.

**Pull request closed without merging**
